# Pertemuan 2 ~ Operasi MatrikS

### Deklarasi

In [14]:
import numpy as np 

#vektor baris (1 x n)
vector = np.array([1,2,3])
print("vektor baris : ")
print(vector)

#2d array matriks 
matrix2d = np.array([[1,2,3], [4,5,6]])
print("matriks 2d : ")
print(matrix2d)

#array multidimensi
mdarray = np.array([[9,8,7], [6,5,4], [3,2,1]])
print("matriks multidimensi : ")
print(mdarray)

arrayA = np.array([[3,2,1], [6,5,4], [9,8,7]])

#penjumlahan
pnjmlh = arrayA + mdarray
print("penjumlahan matriks : ")
print(pnjmlh)

#pengurangan
pngrn = arrayA - mdarray
print("pengurangan matriks : ")
print(pngrn)

#perkalian
prkln = np.dot(arrayA, mdarray)
print("perkalian matriks : ")
print(prkln)

arrayB = np.array([[3,2], [6,4], [9,8]])

#perkalian
prkln = np.dot(arrayA, matrix2d.T)
print("perkalian matriks ngawur: ")
print(prkln)


vektor baris : 
[1 2 3]
matriks 2d : 
[[1 2 3]
 [4 5 6]]
matriks multidimensi : 
[[9 8 7]
 [6 5 4]
 [3 2 1]]
penjumlahan matriks : 
[[12 10  8]
 [12 10  8]
 [12 10  8]]
pengurangan matriks : 
[[-6 -6 -6]
 [ 0  0  0]
 [ 6  6  6]]
perkalian matriks : 
[[ 42  36  30]
 [ 96  81  66]
 [150 126 102]]
perkalian matriks ngawur: 
[[ 10  28]
 [ 28  73]
 [ 46 118]]


### Sistem Persamaan Linear

In [15]:
A = np.array([[1, -2], [12, 5]])
B = np.array([32, 7])
print(np.linalg.solve(A,B))

[  6. -13.]


### Penggabungan Matriks

In [31]:
print("naik")
print(np.vstack((arrayA, mdarray)))
print("turun")
print(np.hstack((arrayA, arrayB)))

naik
[[3 2 1]
 [6 5 4]
 [9 8 7]
 [9 8 7]
 [6 5 4]
 [3 2 1]]
turun
[[3 2 1 3 2]
 [6 5 4 6 4]
 [9 8 7 9 8]]


### Reshape

In [29]:
print(arrayB.reshape(2,3))

[[3 2 6]
 [4 9 8]]


### Flatten

In [28]:

print(arrayA.flatten())

[3 2 1 6 5 4 9 8 7]


### Resize

In [27]:

A = int(input())
B = int(input())

print(np.resize(arrayA, (A,B)))

[[3 2 1 6]
 [5 4 9 8]
 [7 3 2 1]
 [6 5 4 9]]


In [ ]:
#1
mtx3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("No 1 : ")
print(mtx3)

#2
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
print("NO 2 : ")
print(A + B)

#3
C = np.array([[1,0], [0,1]])
D = np.array([[2,3], [4,5]])
print("NO 3 : ")
print(np.dot(C, D))

#4
E = np.array([[1,2,3], [4,5,6]])
print("NO 4 : ")
print(E.T)

#5
F = np.array([[1,2], [3,4]])
G = np.array([10,24])
print("NO 5 : ")
print(np.linalg.solve(F, G))

#6
W = np.array([[1,2], [3,4]])
Y = np.array([[5,6], [7,8]])
print("NO 6 : ")
print("NAIK")
print(np.vstack([W, Y]))
print("BOBOK")
print(np.hstack([W, Y]))

#7
X = np.array([[1,2,3], [4,5,6]])
print("NO 7 : ")
print("2x3")
print(np.reshape(X, (2,3)))
print("3x2")
print(np.reshape(X, (3,2)))

No 1 : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
NO 2 : 
[[ 6  8]
 [10 12]]
NO 3 : 
[[2 3]
 [4 5]]
NO 4 : 
[[1 4]
 [2 5]
 [3 6]]
NO 5 : 
[4. 3.]
NO 6 : 
NAIK
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
BOBOK
[[1 2 5 6]
 [3 4 7 8]]
NO 7 : 
2x3
[[1 2 3]
 [4 5 6]]
3x2
[[1 2]
 [3 4]
 [5 6]]
