# Pertemuan 2: Matriks

### 1. Deklarasi Matriks

In [35]:
matriks = [[1,2,3],[4,5,6]]
print (matriks)

[[1, 2, 3], [4, 5, 6]]


In [36]:
import numpy as np

In [37]:
matriks = np.array([[1,2,3],[4,5,6]])
print (matriks)

[[1 2 3]
 [4 5 6]]


In [38]:
# Skalar
scalar = np.array(5)
print("Skalar:", scalar)

# Vektor baris
row_vector = np.array([1,2,3])
print("Vektor Baris : ", row_vector)

#Vector kolom
col_vector = np.array([[4],[5],[6]])
print("Vektor Kolom:\n", col_vector)

Skalar: 5
Vektor Baris :  [1 2 3]
Vektor Kolom:
 [[4]
 [5]
 [6]]


In [39]:
# Matriks 2D
matriks_2D = np.array([[1,2,3],[7,8,9]])
print("Matriks 2D:\n", matriks_2D)

# Matriks 3x3
matriks_3x3 = np.array([[1,2,3],[7,8,9],[4,5,6]])
print("Matriks 3D:\n", matriks_3x3)

Matriks 2D:
 [[1 2 3]
 [7 8 9]]
Matriks 3D:
 [[1 2 3]
 [7 8 9]
 [4 5 6]]


In [47]:
# Matriks Nolll
zeroes_matrix = np.zeros((3,3))
print("Matriks Nol (3x3):\n", zeroes_matrix)

#ones matrix
ones_matrix = np.ones((2,4))
print("Matriks Elemen Satu (2x4):\n", ones_matrix)

#matrix identitas
identity_matrix = np.eye(4)
print("Matriks Identitas:\n", identity_matrix)

#matriks random
random_matrix = np.random.randint(1,11, size=(3,3))
print("Matriks Acak (3x3) :\n", random_matrix)

Matriks Nol (3x3):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriks Elemen Satu (2x4):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Matriks Identitas:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriks Acak (3x3) :
 [[1 4 2]
 [2 3 4]
 [3 1 4]]


### 2. Akses Elemen Matriks

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

#akses elemen tertentu
print ("Elemen Baris ke-1; Kolom ke-2:", A[0,1])

#akses semua elemen baris tertentu
print ("Isi dari Baris ke-2 : ", A[1,:1]) #setelah : adalah batas ambil

#akses semua elemen kolom tertentu
print ("Isi dari Kolom ke-3 : ", A[:,2])

Elemen Baris ke-1; Kolom ke-2: 2
Isi dari Baris ke-2 :  [4]
Isi dari Kolom ke-3 :  [3 6 9]


### 3. Operasi Elemen Matriks

In [55]:
A = np.array([[1,2],[3,4]])
B = np.array([[4,5],[6,7]])
print ("Matriks A :\n", A)
print ("Matriks B :\n", B)

Matriks A :
 [[1 2]
 [3 4]]
Matriks B :
 [[4 5]
 [6 7]]


In [62]:
#perkalian Matriks
C = A * B
print ("perkalian matriks : \n", C)

#pembagian Matriks
D = A / B
print ("pembagian matriks : \n", D)

#pemangkatan Matriks
E = A ** B
print ("pemangkatan matriks : \n", E)

perkalian matriks : 
 [[ 4 10]
 [18 28]]
pembagian matriks : 
 [[0.25       0.4       ]
 [0.5        0.57142857]]
pemangkatan matriks : 
 [[    1    32]
 [  729 16384]]


### 4. Operasi Aljabar Matriks

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[4,5],[6,7]])

In [80]:
C= np.dot(A,B)
print("Perkalian Matriks Rill :\n", C)

Perkalian Matriks Rill :
 [[16 19]
 [14 17]]


In [81]:
#determinan Matriks
det_A = np.linalg.det(A)
print("Determinan Matriks : \n", det_A)

Determinan Matriks : 
 -2.9999999999999996


In [82]:
#inverss
inv_A = np.linalg.inv(A)
print("Invers Matriks :\n", inv_A)

Invers Matriks :
 [[-0.33333333  0.66666667]
 [ 0.66666667 -0.33333333]]


In [83]:
#transporse matriks
A_T = A.T
print("Transpors Matriks :\n", A_T)

Transpors Matriks :
 [[1 2]
 [2 1]]


In [87]:
#Eigenvalue dan eigenvsctor
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Nilai Eigten :\n", eigenvalues)
print("Vektor Eigen :\n", eigenvectors )

#Rank matriks
rank_A = np.linalg.matrix_rank(A)
print("\nRank Matriks :\n", rank_A)

Nilai Eigten :
 [ 3. -1.]
Vektor Eigen :
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Rank Matriks :
 2


### 5.Sistem Persamaan Linear Aljabar

# x - 2y = 32
# 12x + 5y = 7

In [90]:
#Matriks koefisien
A = np.array([[1,-2],[12,5]])

#vektor konstanta
B = np.array([32,7])

#Invers Matriks
A_inv = np.linalg.inv(A)

#Hitung solusi
X = np.dot(A_inv, B)
print("Hasil :\n",X )


Hasil :
 [  6. -13.]


In [91]:
X = np.linalg.solve(A,B)
print("Solusi dengan np.linalg.solve(A,B) : \n", X)

Solusi dengan np.linalg.solve(A,B) : 
 [  6. -13.]


### 6. Penggabungan Matriks

##### Gabung Horizontal

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.array([[9,10],[11,12]])


H = np.hstack((A,B,C))
print ("Hasil Penggabungan horizontal :\n", H)

Hasil Penggabungan horizontal :
 [[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


#### Gabung Vertikal

In [99]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.array([[9,10],[11,12]])

V = np.vstack((A,B,C))
print ("Hasil Penggabungan vertikal :\n", V)

Hasil Penggabungan vertikal :
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


### 7. Pembentukan Ulang Matriks

##### a. Reshape

In [103]:
import numpy as np
# Matriks awal
A = np.array([1, 2, 3, 4, 5, 6])

# Mengubah bentuk menjadi matriks 2x3
reshaped_A = A.reshape(2, 3)
print("Matriks Reshape 2x3:\n", reshaped_A)

# Mengubah bentuk menjadi matriks 3x2
reshaped_A2 = A.reshape(3, 2)
print("\nMatriks Reshape 3x2:\n", reshaped_A2)


Matriks Reshape 2x3:
 [[1 2 3]
 [4 5 6]]

Matriks Reshape 3x2:
 [[1 2]
 [3 4]
 [5 6]]


##### b. Flatten

In [104]:
# Matriks awal
B = np.array([[1, 2, 3], [4, 5, 6]])
flattened_B = B.flatten()
print("Matriks Diratakan (flatten):", flattened_B)

Matriks Diratakan (flatten): [1 2 3 4 5 6]


##### c. Resize

In [ ]:
# Matriks awal [JIKA JUMLAH INDEX KURANG DARI JUMLAH ISI MATRIKS]
C = np.array([1, 2, 3, 4])
# Mengubah ukuran menjadi 3x3
resized_C = np.resize(C, (3, 3))
print("Matriks Resize 3x3:\n", resized_C)

Matriks Resize 3x3:
 [[1 2 3]
 [4 1 2]
 [3 4 1]]
