# AHP

In [21]:
import numpy as np 
import pandas as pd 
print("Helo World")

Helo World


Penentuan **Alternatif** dan **Kriteria**
- Alternatif:
  - A1: Yamaha
  - A2: Honda
  - A3: Suzuki
  - A4: Kawasaki
- Kriteria:
  - C1: Gaya
  - C2: Keandalan
  - C3: Keekonomisan Bahan Bakar

**Tingkat Kepentingan**:
| Intensitas | Keterangan |
|------------|------------|
| 1 | X dan Y sama penting/baik |
| 2 | X sedikit lebih penting/baik dari Y |
| 3 | X lebih penting/baik dari Y |
| 4 | X jauh lebih penting/baik dari Y |

**Preferensi Kriteria**
1. *Keandalan* dua kali lebih penting dari gaya.
2. *Gaya* tiga kali lebih penting dari keekonomisan bahan bakar.
3. *Keandalan* empat kali lebih penting dari keekonomisan bahan bakar.

**Preferensi Alternatif**
1. Preferensi Gaya:
   - Kawasaki > Honda > Yamaha > Suzuki
2. Preferensi Keandalan:
   - Honda > Yamaha > Kawasaki > Suzuki
3. Nilai Keekonomisan Bahan Bakar:
   - Yamaha  : 60
   - Honda   : 80
   - Suzuki  : 60
   - Kawasaki: 80

In [ ]:
def normalize_comparation(m): #normalisasi matriks
    sumCol = m.sum(axis=0)
    norm = m/sumCol
    return norm

def weight(m): #menghitung bobot
    return np.mean(m, axis=1)

def validity_check(m, w):
    n = len(m)
    
    RI = {
        2: 0.00, 3: 0.58, 4: 0.90, 5: 1.12, 6: 1.24, 7: 1.32, 8: 1.41, 9: 1.45,
        10: 1.51, 11: 1.53, 12: 1.54, 13: 1.56, 14: 1.57
    }
    
    CV = m @ w / w
    print(f"CV: ",(CV),"\n")
    
    eigen = np.mean(CV)
    print(f"Eigen: ", (eigen), "\n")
    
    print(f"CI: ",(RI[n]),"\n")
    
    CI = (eigen - n)/(n-1)
    print(f"CI: ",(CI),"\n")
    
    CR = CI/RI[n]
    print(f"CR: ",(CR),"\n")
    
    if CR <= 0.1:
        print("Bobot Valid")
    else:
        print("Tidak Valid")
    
        
def final_weight(w_alt, w_crit):
    w_fin = w_alt.T @ w_crit
    return w_fin

### Evaluasi dan Bobot Kriteria

#### Matriks Perbandingan Berpasangan Kriteria

In [23]:
A = ["Yamaha", "Honda", "Suzuki", "Kawasaki"]

print("==== Kriteria ====")

MPBK = np.array([
    [1  , 1/2, 3 ],
    [2  , 1  , 4 ],
    [1/3, 1/4, 1 ]
    ])

print(MPBK)

==== Kriteria ====
[[1.         0.5        3.        ]
 [2.         1.         4.        ]
 [0.33333333 0.25       1.        ]]


In [24]:
MPBK_norm = normalize_comparation(MPBK)
print(MPBK_norm)

wk = weight(MPBK_norm)
print(wk)

kCheck = validity_check(MPBK, wk)
print(kCheck)


[[0.3        0.28571429 0.375     ]
 [0.6        0.57142857 0.5       ]
 [0.1        0.14285714 0.125     ]]
[0.3202381  0.55714286 0.12261905]
CV:  [3.01858736 3.02991453 3.00647249] 

Eigen:  3.01832479413957 

CI:  0.58 

CI:  0.009162397069784944 

CR:  0.015797236327215424 

Bobot Valid
None


### Kriteria Keandalan

In [25]:
MPBa = np.array([
    [1, 1/2,	3,	2],
    [2,	1,	4,	3],
    [1/3, 1/4, 1, 1/2],
    [1/2, 1/3, 2, 1]
])

MPBa_norm = normalize_comparation(MPBa)
print(MPBa_norm)

wa = weight(MPBa_norm)
print(wa)

aCheck = validity_check(MPBa, wa)
print(aCheck)

[[0.26086957 0.24       0.3        0.30769231]
 [0.52173913 0.48       0.4        0.46153846]
 [0.08695652 0.12       0.1        0.07692308]
 [0.13043478 0.16       0.2        0.15384615]]
[0.27714047 0.4658194  0.0959699  0.16107023]
CV:  [4.04163398 4.05133544 4.01521752 4.01597107] 

Eigen:  4.03103950215422 

CI:  0.9 

CI:  0.010346500718073415 

CR:  0.011496111908970461 

Bobot Valid
None


### Kriteria Gaya

In [26]:
MPBb = np.array([
    [1, 1/2,	2,	1/3],
    [2,	1,	3,	1/2],
    [1/2, 1/3, 1, 1/4],
    [3, 2, 4, 1]
])

MPBb_norm = normalize_comparation(MPBb)
print(MPBb_norm)

wb = weight(MPBb_norm)
print(wb)

bCheck = validity_check(MPBb, wb)
print(bCheck)

[[0.15384615 0.13043478 0.2        0.16      ]
 [0.30769231 0.26086957 0.3        0.24      ]
 [0.07692308 0.08695652 0.1        0.12      ]
 [0.46153846 0.52173913 0.4        0.48      ]]
[0.16107023 0.27714047 0.0959699  0.4658194 ]
CV:  [4.01597107 4.04163398 4.01521752 4.05133544] 

Eigen:  4.03103950215422 

CI:  0.9 

CI:  0.010346500718073415 

CR:  0.011496111908970461 

Bobot Valid
None


### Kriteria Ekonomis

In [27]:
MPBc = np.array([
    [1, 60/80,	1,	60/80],
    [80/60,	1,	80/60,	1],
    [1, 60/80, 1, 60/80],
    [80/60, 1, 80/60, 1]
])

MPBc_norm = normalize_comparation(MPBc)
print(MPBc_norm)

wc = weight(MPBc_norm)
print(wc)

cCheck = validity_check(MPBc, wc)
print(cCheck)

[[0.21428571 0.21428571 0.21428571 0.21428571]
 [0.28571429 0.28571429 0.28571429 0.28571429]
 [0.21428571 0.21428571 0.21428571 0.21428571]
 [0.28571429 0.28571429 0.28571429 0.28571429]]
[0.21428571 0.28571429 0.21428571 0.28571429]
CV:  [4. 4. 4. 4.] 

Eigen:  4.0 

CI:  0.9 

CI:  0.0 

CR:  0.0 

Bobot Valid
None


In [28]:
w_total = np.array([wb,wa,wc])
print(w_total)

w_final = final_weight(w_total, wk)
print(w_final)

max_index = np.argmax(w_final)
print("Alternatif terbaik adalah ", A[max_index])

[[0.16107023 0.27714047 0.0959699  0.4658194 ]
 [0.27714047 0.4658194  0.0959699  0.16107023]
 [0.21428571 0.28571429 0.21428571 0.28571429]]
[0.23226317 0.3833129  0.11047767 0.27394626]
Alternatif terbaik adalah  Honda
